require 'rspec'
require 'to_query_problems'

describe "Sub Queries Exercises" do
  describe "no_apples_for_blair" do
    it "Finds all the cats that own toys named `Apple` that aren't `Blair`" do
      expect(no_apples_for_blair).to eq([
        ["Bethann"],
        ["Bradford"],
        ["Elaina"],
        ["Eldridge"],
        ["Heriberto"],
        ["Mackenzie"],
        ["Raymon"],
        ["Reynaldo"],
        ["Wilmer"]
    ])
    end
    
    it "SUBQUERY - Finds all the cats that own toys named `Apple` that aren't `Blair`" do
      expect(no_apples_for_blair_sub).to eq([
      ["Bethann"],
      ["Bradford"],
      ["Elaina"],
      ["Eldridge"],
      ["Heriberto"],
      ["Mackenzie"],
      ["Raymon"],
      ["Reynaldo"],
      ["Wilmer"]
      ])
    end
  end

  describe "toys_that_brendon_owns" do
    it "List the all the toy names for all the cats named 'Brendon'" do
      expect(toys_that_brendon_owns).to eq([
        ["Cherry blossom"],
        ["Information desk person"],
        ["Partly sunny"],
        ["Smiley cat"],
        ["Symbols"],
        ["Traffic light"],
        ["Two hearts"]
      ])
    end
    it "SUBQUERY - List the all the toy names for all the cats named 'Brendon'" do
      expect(toys_that_brendon_owns_sub).to eq([
        ["Cherry blossom"],
        ["Information desk person"],
        ["Partly sunny"],
        ["Smiley cat"],
        ["Symbols"],
        ["Traffic light"],
        ["Two hearts"]
      ])
    end
  end

  describe "price_like_shiny_mouse" do
    it "List the name and price of all the toys with the same price as Shiny Mouse (excluding 'Shiny Mouse')" do
      expect(price_like_shiny_mouse).to eq([
        ["Clap", "9"],
        ["Mount fuji", "9"]
      ])
    end
    it "SUBQUERY - List the name and price of all the toys with the same price as Shiny Mouse (excluding 'Shiny Mouse')" do
      expect(price_like_shiny_mouse_sub).to eq([
        ["Clap", "9"],
        ["Mount fuji", "9"]
      ])
    end
  end

  describe "just_like_orange" do
    it "List all the cats of Orange's breed excluding Orange the cat" do
      expect(just_like_orange).to eq([
        ["Abdul", "Brazilian Shorthair"],
        ["Ai", "Brazilian Shorthair"],
        ["Aida", "Brazilian Shorthair"],
        ["Alejandra", "Brazilian Shorthair"],
        ["Allen", "Brazilian Shorthair"],
        ["Alvin", "Brazilian Shorthair"],
        ["Andrea", "Brazilian Shorthair"],
        ["Angie", "Brazilian Shorthair"],
        ["Anna", "Brazilian Shorthair"],
        ["Aracely", "Brazilian Shorthair"],
        ["Arden", "Brazilian Shorthair"],
        ["Arlinda", "Brazilian Shorthair"],
        ["Arron", "Brazilian Shorthair"],
        ["Arthur", "Brazilian Shorthair"],
        ["Ayana", "Brazilian Shorthair"],
        ["Beaulah", "Brazilian Shorthair"],
        ["Bobette", "Brazilian Shorthair"],
        ["Bonita", "Brazilian Shorthair"],
        ["Brianna", "Brazilian Shorthair"],
        ["Bud", "Brazilian Shorthair"],
        ["Candy", "Brazilian Shorthair"],
        ["Cary", "Brazilian Shorthair"],
        ["Chantel", "Brazilian Shorthair"],
        ["Charles", "Brazilian Shorthair"],
        ["Cheri", "Brazilian Shorthair"],
        ["Cherie", "Brazilian Shorthair"],
        ["Chuck", "Brazilian Shorthair"],
        ["Coleen", "Brazilian Shorthair"],
        ["Cori", "Brazilian Shorthair"],
        ["Cruz", "Brazilian Shorthair"],
        ["Dallas", "Brazilian Shorthair"],
        ["Damian", "Brazilian Shorthair"],
        ["Damon", "Brazilian Shorthair"],
        ["Daysi", "Brazilian Shorthair"],
        ["Deena", "Brazilian Shorthair"],
        ["Denyse", "Brazilian Shorthair"],
        ["Dominick", "Brazilian Shorthair"],
        ["Donnie", "Brazilian Shorthair"],
        ["Donny", "Brazilian Shorthair"],
        ["Ed", "Brazilian Shorthair"],
        ["Edgar", "Brazilian Shorthair"],
        ["Edith", "Brazilian Shorthair"],
        ["Edmundo", "Brazilian Shorthair"],
        ["Elia", "Brazilian Shorthair"],
        ["Elijah", "Brazilian Shorthair"],
        ["Estrella", "Brazilian Shorthair"],
        ["Ethan", "Brazilian Shorthair"],
        ["Freeman", "Brazilian Shorthair"],
        ["Giuseppe", "Brazilian Shorthair"],
        ["Glenda", "Brazilian Shorthair"],
        ["Harry", "Brazilian Shorthair"],
        ["Hilde", "Brazilian Shorthair"],
        ["Hollie", "Brazilian Shorthair"],
        ["Hosea", "Brazilian Shorthair"],
        ["Idell", "Brazilian Shorthair"],
        ["In", "Brazilian Shorthair"],
        ["Ione", "Brazilian Shorthair"],
        ["Jani", "Brazilian Shorthair"],
        ["Jannet", "Brazilian Shorthair"],
        ["Jerome", "Brazilian Shorthair"],
        ["Jesus", "Brazilian Shorthair"],
        ["Josef", "Brazilian Shorthair"],
        ["Katlyn", "Brazilian Shorthair"],
        ["Kendall", "Brazilian Shorthair"],
        ["Kenia", "Brazilian Shorthair"],
        ["Khadijah", "Brazilian Shorthair"],
        ["Kimbery", "Brazilian Shorthair"],
        ["Kum", "Brazilian Shorthair"],
        ["Laurena", "Brazilian Shorthair"],
        ["Leisa", "Brazilian Shorthair"],
        ["Lincoln", "Brazilian Shorthair"],
        ["Liz", "Brazilian Shorthair"],
        ["Lore", "Brazilian Shorthair"],
        ["Luann", "Brazilian Shorthair"],
        ["Lucas", "Brazilian Shorthair"],
        ["Luciano", "Brazilian Shorthair"],
        ["Lucretia", "Brazilian Shorthair"],
        ["Lyle", "Brazilian Shorthair"],
        ["Lyndsey", "Brazilian Shorthair"],
        ["Magaret", "Brazilian Shorthair"],
        ["Man", "Brazilian Shorthair"],
        ["Martina", "Brazilian Shorthair"],
        ["Meredith", "Brazilian Shorthair"],
        ["Min", "Brazilian Shorthair"],
        ["Myles", "Brazilian Shorthair"],
        ["Napoleon", "Brazilian Shorthair"],
        ["Nelly", "Brazilian Shorthair"],
        ["Norman", "Brazilian Shorthair"],
        ["Pauline", "Brazilian Shorthair"],
        ["Randee", "Brazilian Shorthair"],
        ["Regina", "Brazilian Shorthair"],
        ["Reita", "Brazilian Shorthair"],
        ["Rick", "Brazilian Shorthair"],
        ["Robin", "Brazilian Shorthair"],
        ["Rochelle", "Brazilian Shorthair"],
        ["Roger", "Brazilian Shorthair"],
        ["Russell", "Brazilian Shorthair"],
        ["Serina", "Brazilian Shorthair"],
        ["Seymour", "Brazilian Shorthair"],
        ["Sharita", "Brazilian Shorthair"],
        ["Soledad", "Brazilian Shorthair"],
        ["Sona", "Brazilian Shorthair"],
        ["Sung", "Brazilian Shorthair"],
        ["Sydney", "Brazilian Shorthair"],
        ["Teresa", "Brazilian Shorthair"],
        ["Trisha", "Brazilian Shorthair"],
        ["Ty", "Brazilian Shorthair"],
        ["Wendell", "Brazilian Shorthair"],
        ["Wendy", "Brazilian Shorthair"],
        ["Willis", "Brazilian Shorthair"],
        ["Winfred", "Brazilian Shorthair"],
        ["Zula", "Brazilian Shorthair"]
      ])
    end
    it "SUBQUERY - List all the cats of Orange's breed excluding Orange the cat" do
      expect(just_like_orange_sub).to eq([
        ["Abdul", "Brazilian Shorthair"],
        ["Ai", "Brazilian Shorthair"],
        ["Aida", "Brazilian Shorthair"],
        ["Alejandra", "Brazilian Shorthair"],
        ["Allen", "Brazilian Shorthair"],
        ["Alvin", "Brazilian Shorthair"],
        ["Andrea", "Brazilian Shorthair"],
        ["Angie", "Brazilian Shorthair"],
        ["Anna", "Brazilian Shorthair"],
        ["Aracely", "Brazilian Shorthair"],
        ["Arden", "Brazilian Shorthair"],
        ["Arlinda", "Brazilian Shorthair"],
        ["Arron", "Brazilian Shorthair"],
        ["Arthur", "Brazilian Shorthair"],
        ["Ayana", "Brazilian Shorthair"],
        ["Beaulah", "Brazilian Shorthair"],
        ["Bobette", "Brazilian Shorthair"],
        ["Bonita", "Brazilian Shorthair"],
        ["Brianna", "Brazilian Shorthair"],
        ["Bud", "Brazilian Shorthair"],
        ["Candy", "Brazilian Shorthair"],
        ["Cary", "Brazilian Shorthair"],
        ["Chantel", "Brazilian Shorthair"],
        ["Charles", "Brazilian Shorthair"],
        ["Cheri", "Brazilian Shorthair"],
        ["Cherie", "Brazilian Shorthair"],
        ["Chuck", "Brazilian Shorthair"],
        ["Coleen", "Brazilian Shorthair"],
        ["Cori", "Brazilian Shorthair"],
        ["Cruz", "Brazilian Shorthair"],
        ["Dallas", "Brazilian Shorthair"],
        ["Damian", "Brazilian Shorthair"],
        ["Damon", "Brazilian Shorthair"],
        ["Daysi", "Brazilian Shorthair"],
        ["Deena", "Brazilian Shorthair"],
        ["Denyse", "Brazilian Shorthair"],
        ["Dominick", "Brazilian Shorthair"],
        ["Donnie", "Brazilian Shorthair"],
        ["Donny", "Brazilian Shorthair"],
        ["Ed", "Brazilian Shorthair"],
        ["Edgar", "Brazilian Shorthair"],
        ["Edith", "Brazilian Shorthair"],
        ["Edmundo", "Brazilian Shorthair"],
        ["Elia", "Brazilian Shorthair"],
        ["Elijah", "Brazilian Shorthair"],
        ["Estrella", "Brazilian Shorthair"],
        ["Ethan", "Brazilian Shorthair"],
        ["Freeman", "Brazilian Shorthair"],
        ["Giuseppe", "Brazilian Shorthair"],
        ["Glenda", "Brazilian Shorthair"],
        ["Harry", "Brazilian Shorthair"],
        ["Hilde", "Brazilian Shorthair"],
        ["Hollie", "Brazilian Shorthair"],
        ["Hosea", "Brazilian Shorthair"],
        ["Idell", "Brazilian Shorthair"],
        ["In", "Brazilian Shorthair"],
        ["Ione", "Brazilian Shorthair"],
        ["Jani", "Brazilian Shorthair"],
        ["Jannet", "Brazilian Shorthair"],
        ["Jerome", "Brazilian Shorthair"],
        ["Jesus", "Brazilian Shorthair"],
        ["Josef", "Brazilian Shorthair"],
        ["Katlyn", "Brazilian Shorthair"],
        ["Kendall", "Brazilian Shorthair"],
        ["Kenia", "Brazilian Shorthair"],
        ["Khadijah", "Brazilian Shorthair"],
        ["Kimbery", "Brazilian Shorthair"],
        ["Kum", "Brazilian Shorthair"],
        ["Laurena", "Brazilian Shorthair"],
        ["Leisa", "Brazilian Shorthair"],
        ["Lincoln", "Brazilian Shorthair"],
        ["Liz", "Brazilian Shorthair"],
        ["Lore", "Brazilian Shorthair"],
        ["Luann", "Brazilian Shorthair"],
        ["Lucas", "Brazilian Shorthair"],
        ["Luciano", "Brazilian Shorthair"],
        ["Lucretia", "Brazilian Shorthair"],
        ["Lyle", "Brazilian Shorthair"],
        ["Lyndsey", "Brazilian Shorthair"],
        ["Magaret", "Brazilian Shorthair"],
        ["Man", "Brazilian Shorthair"],
        ["Martina", "Brazilian Shorthair"],
        ["Meredith", "Brazilian Shorthair"],
        ["Min", "Brazilian Shorthair"],
        ["Myles", "Brazilian Shorthair"],
        ["Napoleon", "Brazilian Shorthair"],
        ["Nelly", "Brazilian Shorthair"],
        ["Norman", "Brazilian Shorthair"],
        ["Pauline", "Brazilian Shorthair"],
        ["Randee", "Brazilian Shorthair"],
        ["Regina", "Brazilian Shorthair"],
        ["Reita", "Brazilian Shorthair"],
        ["Rick", "Brazilian Shorthair"],
        ["Robin", "Brazilian Shorthair"],
        ["Rochelle", "Brazilian Shorthair"],
        ["Roger", "Brazilian Shorthair"],
        ["Russell", "Brazilian Shorthair"],
        ["Serina", "Brazilian Shorthair"],
        ["Seymour", "Brazilian Shorthair"],
        ["Sharita", "Brazilian Shorthair"],
        ["Soledad", "Brazilian Shorthair"],
        ["Sona", "Brazilian Shorthair"],
        ["Sung", "Brazilian Shorthair"],
        ["Sydney", "Brazilian Shorthair"],
        ["Teresa", "Brazilian Shorthair"],
        ["Trisha", "Brazilian Shorthair"],
        ["Ty", "Brazilian Shorthair"],
        ["Wendell", "Brazilian Shorthair"],
        ["Wendy", "Brazilian Shorthair"],
        ["Willis", "Brazilian Shorthair"],
        ["Winfred", "Brazilian Shorthair"],
        ["Zula", "Brazilian Shorthair"]
      ])
    end
  end

  describe "toys_that_jet_owns" do
    it "Show toys that Jets owns and shows all the cats who own that toy (excluding Jet)" do
      expect(toys_that_jet_owns).to eq([
        ["Alline", "Rice"],
        ["Anika", "Couple"],
        ["Avery", "Construction"],
        ["Brady", "Rice"],
        ["Brittani", "Yen"],
        ["Carl", "Couple"],
        ["Carter", "Light rail"],
        ["Christoper", "Couple"],
        ["Clyde", "Rice"],
        ["Columbus", "Pound"],
        ["Debrah", "Construction"],
        ["Delena", "Ear of rice"],
        ["Delores", "Station"],
        ["Denisha", "Jp"],
        ["Destiny", "Station"],
        ["Dominic", "Neutral face"],
        ["Earl", "Rice"],
        ["Eboni", "Rice"],
        ["Eden", "Minibus"],
        ["Essie", "Yen"],
        ["Federico", "Light rail"],
        ["Gary", "Office"],
        ["Georgette", "Couple"],
        ["Gregg", "Office"],
        ["Hang", "Yen"],
        ["Herbert", "Office"],
        ["Herta", "Mountain cableway"],
        ["Hung", "Couple"],
        ["Ian", "Neutral face"],
        ["Irving", "Couple"],
        ["Jeremiah", "Office"],
        ["Jovita", "Station"],
        ["Julian", "Pound"],
        ["Kendall", "Suspect"],
        ["Kennith", "Japanese castle"],
        ["Lauran", "Mountain cableway"],
        ["Leonard", "Japanese castle"],
        ["Lianne", "Construction"],
        ["Lily", "Neutral face"],
        ["Lindsey", "Love hotel"],
        ["Mario", "Ear of rice"],
        ["Markus", "Pray"],
        ["Marlin", "Suspect"],
        ["May", "Construction"],
        ["Myong", "Pound"],
        ["Nickolas", "Suspect"],
        ["Oren", "It"],
        ["Paige", "Couple"],
        ["Pierre", "Station"],
        ["Providencia", "Rice"],
        ["Quyen", "Japan"],
        ["Sarai", "Jp"],
        ["Shanda", "Suspect"],
        ["Sol", "Light rail"],
        ["Stanford", "Light rail"],
        ["Terese", "Station"],
        ["Thu", "Office"],
        ["Tommie", "Neutral face"],
        ["Tu", "Office"],
        ["Williemae", "It"],
        ["Winnie", "Love hotel"],
        ["Yun", "Love hotel"]
      ])
    end
      
    it "SUBQUERY - Show toys that Jets owns and shows all the cats who own that toy (excluding Jet)" do
      expect(toys_that_jet_owns_sub).to eq([
        ["Alline", "Rice"],
        ["Anika", "Couple"],
        ["Avery", "Construction"],
        ["Brady", "Rice"],
        ["Brittani", "Yen"],
        ["Carl", "Couple"],
        ["Carter", "Light rail"],
        ["Christoper", "Couple"],
        ["Clyde", "Rice"],
        ["Columbus", "Pound"],
        ["Debrah", "Construction"],
        ["Delena", "Ear of rice"],
        ["Delores", "Station"],
        ["Denisha", "Jp"],
        ["Destiny", "Station"],
        ["Dominic", "Neutral face"],
        ["Earl", "Rice"],
        ["Eboni", "Rice"],
        ["Eden", "Minibus"],
        ["Essie", "Yen"],
        ["Federico", "Light rail"],
        ["Gary", "Office"],
        ["Georgette", "Couple"],
        ["Gregg", "Office"],
        ["Hang", "Yen"],
        ["Herbert", "Office"],
        ["Herta", "Mountain cableway"],
        ["Hung", "Couple"],
        ["Ian", "Neutral face"],
        ["Irving", "Couple"],
        ["Jeremiah", "Office"],
        ["Jovita", "Station"],
        ["Julian", "Pound"],
        ["Kendall", "Suspect"],
        ["Kennith", "Japanese castle"],
        ["Lauran", "Mountain cableway"],
        ["Leonard", "Japanese castle"],
        ["Lianne", "Construction"],
        ["Lily", "Neutral face"],
        ["Lindsey", "Love hotel"],
        ["Mario", "Ear of rice"],
        ["Markus", "Pray"],
        ["Marlin", "Suspect"],
        ["May", "Construction"],
        ["Myong", "Pound"],
        ["Nickolas", "Suspect"],
        ["Oren", "It"],
        ["Paige", "Couple"],
        ["Pierre", "Station"],
        ["Providencia", "Rice"],
        ["Quyen", "Japan"],
        ["Sarai", "Jp"],
        ["Shanda", "Suspect"],
        ["Sol", "Light rail"],
        ["Stanford", "Light rail"],
        ["Terese", "Station"],
        ["Thu", "Office"],
        ["Tommie", "Neutral face"],
        ["Tu", "Office"],
        ["Williemae", "It"],
        ["Winnie", "Love hotel"],
        ["Yun", "Love hotel"]
      ])
    end
  end
end
